import { adjust, updateStudent, undo } from "@/app/actions";
import { requireTeacher } from "@/lib/auth";
import { db } from "@/lib/db";
import { notFound } from "next/navigation";

export default async function StudentDetail({ params }: { params: Promise<{ studentId: string }> }) {
  const teacher = await requireTeacher(); const { studentId } = await params;
  const student = await db.student.findFirst({ where: { id: studentId, teacherId: teacher.id }, include: { classroom: true, transactions: { orderBy: { createdAt: "desc" }, include: { correctedBy: true } }, assignments: { where: { endedAt: null }, include: { card: true } } } });
  if (!student) notFound(); const total = student.transactions.reduce((sum, item) => sum + item.amount, 0);
  return <div className="grid gap-6"><section className="panel overflow-hidden"><div className="bg-[#23312c] p-7 text-white"><p>{student.classroom?.name ?? "Unassigned"}</p><h1 className="mt-2 text-4xl">{student.displayName}</h1><p className="display mt-5 text-6xl text-[#f9bd72]">{student.classroom?.currencySymbol}{total}</p></div><div className="grid gap-4 p-5 md:grid-cols-2"><p>Assigned card: <strong>{student.assignments[0] ? `#${student.assignments[0].card.label} · ${student.assignments[0].card.shortCode}` : "None"}</strong></p><form action={updateStudent} className="flex gap-2"><input type="hidden" name="studentId" value={student.id} /><input type="hidden" name="active" value={String(student.active)} /><input className="field" name="displayName" defaultValue={student.displayName} aria-label="Student name" required /><button className="btn btn-soft">Save name</button></form><form action={updateStudent} className="flex gap-2"><input type="hidden" name="studentId" value={student.id} /><input type="hidden" name="active" value={String(!student.active)} /><input type="hidden" name="displayName" value={student.displayName} /><button className="btn btn-soft">{student.active ? "Deactivate student" : "Reactivate student"}</button></form></div></section>
    {student.active && student.classroom && !student.classroom.archived && <form action={adjust} className="panel grid gap-3 p-5 md:grid-cols-[140px_140px_1fr_auto]"><input type="hidden" name="studentId" value={student.id} /><select className="field" name="direction"><option value="add">Add</option><option value="remove">Remove</option></select><input className="field" type="number" min="1" step="1" name="amount" placeholder="Amount" required /><input className="field" name="reason" placeholder="Required reason" required /><button className="btn btn-accent">Post adjustment</button></form>}
    <section className="panel overflow-hidden"><h2 className="p-5 text-2xl">Transaction history</h2>{student.transactions.map((entry) => <div className="grid grid-cols-[1fr_auto] gap-3 border-t border-black/10 p-4" key={entry.id}><div>{entry.reason && <strong>{entry.reason}</strong>}<p className="text-sm text-slate-500">{entry.kind} · {entry.createdAt.toLocaleString()}</p></div><div className="text-right"><span className={`display text-xl ${entry.amount > 0 ? "text-green-700" : "text-red-700"}`}>{entry.amount > 0 ? "+" : ""}{entry.amount}</span>{!student.classroom?.archived && !entry.correctedBy && entry.kind !== "CORRECTION" && <form action={undo}><input type="hidden" name="transactionId" value={entry.id} /><button className="mt-1 block text-xs underline">Undo</button></form>}</div></div>)}{!student.transactions.length && <p className="p-8 text-center">No transactions yet.</p>}</section>
  </div>;
}
