import Link from "next/link";
import { addStudents, moveStudents, removeStudents, resetAssignments, savePreset, setArchived, updateClassroom } from "@/app/actions";
import { requireTeacher } from "@/lib/auth";
import { ownedClassroom } from "@/lib/classes";
import { db } from "@/lib/db";
import { CsvNames } from "@/components/CsvNames";
import { balancesByStudent } from "@/lib/ledger";
import { DeleteClassroomButton } from "@/components/DeleteClassroomButton";

export default async function Roster({ params, searchParams }: { params: Promise<{ classroomId: string }>; searchParams: Promise<{ sort?: string }> }) {
  const teacher = await requireTeacher();
  const { classroomId } = await params;
  const [classroom, students, destinations, presets] = await Promise.all([
    ownedClassroom(teacher.id, classroomId),
    db.student.findMany({ where: { classroomId, teacherId: teacher.id }, include: { assignments: { where: { endedAt: null }, include: { card: true } } } }),
    db.classroom.findMany({ where: { teacherId: teacher.id, archived: false, NOT: { id: classroomId } } }),
    db.awardPreset.findMany({ where: { classroomId }, orderBy: { sortOrder: "asc" } }),
  ]);
  const balances = await balancesByStudent(students.map((student) => student.id));
  const rows = students.map((student) => ({ ...student, balance: balances.get(student.id) ?? 0 }));
  const sort = (await searchParams).sort;
  rows.sort(sort === "balance" ? (a, b) => b.balance - a.balance : (a, b) => a.displayName.localeCompare(b.displayName));

  return <div className="grid gap-6">
    <div><p className="font-bold text-[#e85d43]">{classroom.name}</p><h1 className="text-4xl">Roster</h1></div>
    <div className="grid grid-cols-2 gap-2 sm:flex"><Link className="btn btn-soft" href="?sort=name">Sort A-Z</Link><Link className="btn btn-soft" href="?sort=balance">Sort by balance</Link><a className="btn col-span-2" href={`/api/export/${classroomId}`}>Export transactions</a><DeleteClassroomButton classroomId={classroomId} classroomName={classroom.name} /></div>
    {!classroom.archived && <details className="panel p-5"><summary className="font-bold">Bulk add students</summary><form action={addStudents} className="mt-4 grid gap-3"><input type="hidden" name="classroomId" value={classroomId} /><label className="label">Student names<textarea className="field min-h-36" name="names" placeholder="Avery Johnson, Sam Rivera, Jordan Lee" required /></label><p className="text-sm text-slate-600">Separate names with commas or put one name on each line.</p><CsvNames /><button className="btn btn-accent">Add students</button></form></details>}
    <section className="panel overflow-hidden"><form action={moveStudents} id="selected-students"><div className="grid gap-3 border-b border-black/10 p-4 md:grid-cols-[1fr_240px_auto_auto]"><strong>Select students</strong><select className="field" name="destinationId"><option value="">Destination class</option>{destinations.map((room) => <option value={room.id} key={room.id}>{room.name}</option>)}</select><button className="btn">Move selected</button><button className="btn btn-soft text-red-700" formAction={removeStudents}>Remove selected</button><input type="hidden" name="classroomId" value={classroomId} /></div></form>{rows.map((student) => <div className="grid min-h-20 grid-cols-[28px_1fr_auto] items-center gap-3 border-b border-black/5 px-4 py-3 sm:grid-cols-[28px_1fr_auto_auto]" key={student.id}><input className="h-5 w-5" aria-label={`Select ${student.displayName}`} type="checkbox" name="studentIds" value={student.id} form="selected-students" /><span><Link className="font-bold underline" href={`/app/student/${student.id}`}>{student.displayName}</Link><Link className="ml-2 text-sm underline" href={`/app/student/${student.id}`}>Edit name</Link>{!student.active && <small className="ml-2 text-red-700">Inactive</small>}<small className="mt-1 block text-slate-500 sm:hidden">{student.assignments[0] ? `Card ${student.assignments[0].card.label}` : "No card"}</small></span><span className="display text-xl">{classroom.currencySymbol}{student.balance}</span><span className="hidden text-sm sm:block">{student.assignments[0] ? `Card ${student.assignments[0].card.label}` : "No card"}</span></div>)}{!rows.length && <p className="p-8 text-center">No students are in this classroom.</p>}</section>
    <details className="panel p-5"><summary className="font-bold">Classroom settings</summary><form action={updateClassroom} className="mt-4 grid gap-3 md:grid-cols-5"><input type="hidden" name="classroomId" value={classroomId} /><input className="field" name="name" defaultValue={classroom.name} required /><input className="field" name="schoolYear" defaultValue={classroom.schoolYear} required /><input className="field" name="currencyName" defaultValue={classroom.currencyName} required /><input className="field" name="currencySymbol" defaultValue={classroom.currencySymbol} required /><button className="btn">Save</button></form><h3 className="mt-6 text-lg">Award presets</h3><div className="mt-2 grid gap-2"><div className="hidden grid-cols-[1fr_100px_auto] gap-2 px-1 text-xs font-bold uppercase tracking-wide text-slate-600 md:grid"><span>Label</span><span>Amount</span><span>Action</span></div>{presets.map((preset) => <form action={savePreset} className="grid gap-2 md:grid-cols-[1fr_100px_auto]" key={preset.id}><input type="hidden" name="classroomId" value={classroomId} /><input type="hidden" name="presetId" value={preset.id} /><input className="field" name="label" defaultValue={preset.label} aria-label="Preset label" /><input className="field" name="amount" type="number" min="1" defaultValue={preset.amount} aria-label="Preset amount" /><button className="btn btn-soft">Save</button></form>)}{!classroom.archived && <form action={savePreset} className="grid gap-2 md:grid-cols-[1fr_100px_auto]"><input type="hidden" name="classroomId" value={classroomId} /><input className="field" name="label" placeholder="New preset" required aria-label="New preset label" /><input className="field" name="amount" type="number" min="1" placeholder="Amount" required aria-label="New preset amount" /><button className="btn">Add</button></form>}</div><div className="mt-5 flex flex-wrap gap-3"><form action={setArchived}><input type="hidden" name="classroomId" value={classroomId} /><input type="hidden" name="archived" value={String(!classroom.archived)} /><button className="btn btn-soft">{classroom.archived ? "Restore classroom" : "Archive classroom"}</button></form>{!classroom.archived && <form action={resetAssignments}><input type="hidden" name="classroomId" value={classroomId} /><button className="btn btn-soft">Remove all card assignments</button></form>}</div></details>
  </div>;
}
